apiVersion: v1
kind: Service
metadata: { name: sample-svc, namespace: demo }
spec:
  type: NodePort
  selector: { app: sample-app }
  ports: [{ name: http, port: 80, targetPort: 80, nodePort: 30080 }]
